/**
 * ---------------------------------------
 * This demo was created using amCharts 4.
 *
 * For more information visit:
 * https://www.amcharts.com/
 *
 * Documentation is available at:
 * https://www.amcharts.com/docs/v4/
 * ---------------------------------------
 */

// Create map instance
var chart = am4core.create("chartdiv", am4maps.MapChart);

// Set map definition
chart.geodata = am4geodata_worldLow;

// Set projection
chart.projection = new am4maps.projections.Miller();

// Create map polygon series
var polygonSeries = chart.series.push(new am4maps.MapPolygonSeries());

// Make map load polygon (like country names) data from GeoJSON
polygonSeries.useGeodata = true;

// Configure series
var polygonTemplate = polygonSeries.mapPolygons.template;
polygonTemplate.tooltipText = "{name}: {value}";
polygonTemplate.fill = am4core.color("#999");

// Create hover state and set alternative fill color
var hs = polygonTemplate.states.create("hover");
hs.properties.fill = am4core.color("#014B64");

// Remove Antarctica
polygonSeries.exclude = ["AQ"];

// Add heat rule
polygonSeries.heatRules.push({
  "property": "fill",
  "target": polygonSeries.mapPolygons.template,
  "min": am4core.color("#01505F"),
  "max": am4core.color("#ffffff")
});

// Add expectancy data

polygonSeries.data = [
  {name: 'Afghanistan', id: 'AF', value: 74},
  // {name: 'Åland Islands', id: 'AX'},
  {name: 'Albania', id: 'AL', value: 113.50},
  {name: 'Algeria', id: 'DZ', value: 92.83},
  // {name: 'American Samoa', id: 'AS'},
  // {name: 'AndorrA', id: 'AD'},
  {name: 'Angola', id: 'AO', value: 84},
  // {name: 'Anguilla', id: 'AI'},
  // {name: 'Antarctica', id: 'AQ'},
  {name: 'Antigua and Barbuda', id: 'AG', value: 64.5},
  {name: 'Argentina', id: 'AR', value: 77},
  {name: 'Armenia', id: 'AM', value: 142.83},
  // {name: 'Aruba', id: 'AW'},
  {name: 'Australia', id: 'AU', value: 47.67},
  {name: 'Austria', id: 'AT', value: 56.5},
  {name: 'Azerbaijan', id: 'AZ', value: 133.5},
  {name: 'Bahamas', id: 'BS', value: 27},
  {name: 'Bahrain', id: 'BH', value: 170.83},
  {name: 'Bangladesh', id: 'BD', value: 28.33},
  {name: 'Barbados', id: 'BB', value: 135.33},
  {name: 'Belarus', id: 'BY', value: 156.17},
  {name: 'Belgium', id: 'BE', value: 63.67},
  {name: 'Belize', id: 'BZ', value: 48.67},
  {name: 'Benin', id: 'BJ', value: 139.83},
  // {name: 'Bermuda', id: 'BM',},
  {name: 'Bhutan', id: 'BT', value: 95.17},
  {name: 'Bolivia', id: 'BO', value: 40.17},
  {name: 'Bosnia and Herzegovina', id: 'BA', value: 68.17},
  {name: 'Botswana', id: 'BW', value: 130.17},
  // {name: 'Bouvet Island', id: 'BV'},
  {name: 'Brazil', id: 'BR', value: 79.5},
  // {name: 'British Indian Ocean Territory', id: 'IO'},
  {name: 'Brunei Darussalam', id: 'BN', value: 167.5},
  {name: 'Bulgaria', id: 'BG', value: 71.67},
  {name: 'Burkina Faso', id: 'BF', value: 101},
  {name: 'Burundi', id: 'BI', value: 74.5},
  {name: 'Cambodia', id: 'KH', value: 36.17},
  {name: 'Cameroon', id: 'CM', value: 128.17},
  {name: 'Canada', id: 'CA', value: 87.33},
  {name: 'Cape Verde', id: 'CV', value: 137.67},
  // {name: 'Cayman Islands', id: 'KY'},
  {name: 'Central African Republic', id: 'CF', value: 138.83},
  {name: 'Chad', id: 'TD', value: 104.67},
  {name: 'Chile', id: 'CL', value: 81.33},
  {name: 'China', id: 'CN', value: 56.33},
  // {name: 'Christmas Island', id: 'CX'},
  // {name: 'Cocos (Keeling) Islands', id: 'CC'},
  {name: 'Colombia', id: 'CO', value: 54.83},
  {name: 'Comoros', id: 'KM', value: 90},
  {name: 'Congo', id: 'CG', value: 148.33},
  {name: 'Congo, The Democratic Republic of the', id: 'CD', value: 118},
  // {name: 'Cook Islands', id: 'CK'},
  {name: 'Costa Rica', id: 'CR', value: 84.5},
  {name: 'Cote D\'Ivoire', id: 'CI', value: 141.33},
  {name: 'Croatia', id: 'HR', value: 47},
  // {name: 'Cuba', id: 'CU'},
  {name: 'Cyprus', id: 'CY', value: 129.67},
  {name: 'Czech Republic', id: 'CZ', value: 80.67},
  {name: 'Denmark', id: 'DK', value: 118.83},
  {name: 'Djibouti', id: 'DJ', value: 70.33},
  {name: 'Dominica', id: 'DM', value: 33},
  {name: 'Dominican Republic', id: 'DO', value: 59.5},
  {name: 'Ecuador', id: 'EC', value: 94.17},
  {name: 'Egypt', id: 'EG', value: 142.17},
  {name: 'El Salvador', id: 'SV', value: 43.67},
  // {name: 'Equatorial Guinea', id: 'GQ'},
  {name: 'Eritrea', id: 'ER', value: 115.83},
  {name: 'Estonia', id: 'EE', value: 144.5},
  {name: 'Ethiopia', id: 'ET', value: 66.5},
  // {name: 'Falkland Islands (Malvinas)', id: 'FK'},
  // {name: 'Faroe Islands', id: 'FO'},
  {name: 'Fiji', id: 'FJ', value: 38.33},
  {name: 'Finland', id: 'FI', value: 153.5},
  {name: 'France', id: 'FR', value: 41.67},
  // {name: 'French Guiana', id: 'GF'},
  // {name: 'French Polynesia', id: 'PF'},
  // {name: 'French Southern Territories', id: 'TF'},
  {name: 'Gabon', id: 'GA', value: 165.83},
  {name: 'Gambia', id: 'GM', value: 93},
  {name: 'Georgia', id: 'GE', value: 94.67},
  {name: 'Germany', id: 'DE', value: 38.17},
  {name: 'Ghana', id: 'GH', value: 101.33},
  // {name: 'Gibraltar', id: 'GI'},
  {name: 'Greece', id: 'GR', value: 75},
  // {name: 'Greenland', id: 'GL'},
  {name: 'Grenada', id: 'GD', value: 39.67},
  // {name: 'Guadeloupe', id: 'GP', value: 37.5},
  // {name: 'Guam', id: 'GU'},
  {name: 'Guatemala', id: 'GT', value: 37.5},
  // {name: 'Guernsey', id: 'GG'},
  {name: 'Guinea', id: 'GN', value: 159.83},
  {name: 'Guinea-Bissau', id: 'GW', value: 99.17},
  {name: 'Guyana', id: 'GY', value: 108.17},
  {name: 'Haiti', id: 'HT', value: 13.67},
  // {name: 'Heard Island and Mcdonald Islands', id: 'HM'},
  // {name: 'Holy See (Vatican City State)', id: 'VA'},
  {name: 'Honduras', id: 'HN', value: 57},
  {name: 'Hong Kong', id: 'HK'},
  {name: 'Hungary', id: 'HU', value: 74},
  {name: 'Iceland', id: 'IS', value: 168.5},
  {name: 'India', id: 'IN', value: 38.5},
  {name: 'Indonesia', id: 'ID', value: 74},
  {name: 'Iran, Islamic Republic Of', id: 'IR', value: 90},
  {name: 'Iraq', id: 'IQ', value: 143.17},
  {name: 'Ireland', id: 'IE', value: 121.17},
  // {name: 'Isle of Man', id: 'IM'},
  {name: 'Israel', id: 'IL', value: 121.17},
  {name: 'Italy', id: 'IT', value: 39},
  {name: 'Jamaica', id: 'JM', value: 63.83},
  {name: 'Japan', id: 'JP', value: 64.83},
  // {name: 'Jersey', id: 'JE'},
  {name: 'Jordan', id: 'JO', value: 129.5},
  {name: 'Kazakhstan', id: 'KZ', value: 141.83},
  {name: 'Kenya', id: 'KE', value: 52},
  {name: 'Kiribati', id: 'KI', value: 116.33},
  // {name: 'Korea, Democratic People\'S Republic of', id: 'KP'},
  {name: 'Korea, Republic of', id: 'KR', value: 85.17},
  {name: 'Kuwait', id: 'KW', value: 152},
  {name: 'Kyrgyzstan', id: 'KG', value: 109.67},
  {name: 'Lao People\'S Democratic Republic', id: 'LA', value: 60.5},
  {name: 'Latvia', id: 'LV', value: 82.83},
  {name: 'Lebanon', id: 'LB', value: 118},
  {name: 'Lesotho', id: 'LS', value: 99.17},
  {name: 'Liberia', id: 'LR', value: 154.83},
  {name: 'Libyan Arab Jamahiriya', id: 'LY', value: 160.33},
  // {name: 'Liechtenstein', id: 'LI'},
  {name: 'Lithuania', id: 'LT', value: 118.17},
  {name: 'Luxembourg', id: 'LU', value: 89},
  // {name: 'Macao', id: 'MO'},
  {name: 'Macedonia, The Former Yugoslav Republic of', id: 'MK', value: 98},
  {name: 'Madagascar', id: 'MG', value: 34.67},
  {name: 'Malawi', id: 'MW', value: 67.83},
  {name: 'Malaysia', id: 'MY', value: 105.67},
  {name: 'Maldives', id: 'MV', value: 166.83},
  {name: 'Mali', id: 'ML', value: 110.5},
  {name: 'Malta', id: 'MT', value: 134},
  {name: 'Marshall Islands', id: 'MH', value: 164.83},
  // {name: 'Martinique', id: 'MQ'},
  {name: 'Mauritania', id: 'MR', value: 82},
  {name: 'Mauritius', id: 'MU', value: 124.17},
  // {name: 'Mayotte', id: 'YT'},
  {name: 'Mexico', id: 'MX', value: 65.5},
  {name: 'Micronesia, Federated States of', id: 'FM', value: 55.67},
  {name: 'Moldova, Republic of', id: 'MD', value: 81.67},
  // {name: 'Monaco', id: 'MC'},
  {name: 'Mongolia', id: 'MN', value: 59.17},
  // {name: 'Montserrat', id: 'MS'},
  {name: 'Morocco', id: 'MA', value: 96.17},
  {name: 'Mozambique', id: 'MZ', value: 25.83},
  {name: 'Myanmar', id: 'MM', value: 10},
  {name: 'Namibia', id: 'NA', value: 64.33},
  // {name: 'Nauru', id: 'NR'},
  {name: 'Nepal', id: 'NP', value: 31.33},
  {name: 'Netherlands', id: 'NL', value: 72.5},
  // {name: 'Netherlands Antilles', id: 'AN'},
  // {name: 'New Caledonia', id: 'NC'},
  {name: 'New Zealand', id: 'NZ', value: 85},
  {name: 'Nicaragua', id: 'NI', value: 53},
  {name: 'Niger', id: 'NE', value: 68.67},
  {name: 'Nigeria', id: 'NG', value: 109},
  // {name: 'Niue', id: 'NU'},
  // {name: 'Norfolk Island', id: 'NF'},
  // {name: 'Northern Mariana Islands', id: 'MP'},
  {name: 'Norway', id: 'NO', value: 137.5},
  {name: 'Oman', id: 'OM', value: 41.17},
  {name: 'Pakistan', id: 'PK', value: 29},
  // {name: 'Palau', id: 'PW'},
  // {name: 'Palestinian Territory, Occupied', id: 'PS'},
  {name: 'Panama', id: 'PA', value: 107},
  {name: 'Papua New Guinea', id: 'PG', value: 90.83},
  {name: 'Paraguay', id: 'PY', value: 67},
  {name: 'Peru', id: 'PE', value: 57.67},
  {name: 'Philippines', id: 'PH', value: 18.17},
  // {name: 'Pitcairn', id: 'PN'},
  {name: 'Poland', id: 'PL', value: 75.17},
  {name: 'Portugal', id: 'PT', value: 38.67},
  {name: 'Puerto Rico', id: 'PR', value: 7.17},
  {name: 'Qatar', id: 'QA', value: 173.67},
  // {name: 'Reunion', id: 'RE'},
  {name: 'Romania', id: 'RO', value: 56.33},
  {name: 'Russian Federation', id: 'RU', value: 48.5},
  {name: 'Rwanda', id: 'RW', value: 105.83},
  // {name: 'Saint Helena', id: 'SH'},
  // {name: 'Saint Kitts and Nevis', id: 'KN'},
  // {name: 'Saint Lucia', id: 'LC'},
  // {name: 'Saint Pierre and Miquelon', id: 'PM'},
  // {name: 'Saint Vincent and the Grenadines', id: 'VC'},
  {name: 'Samoa', id: 'WS', value: 72.67},
  // {name: 'San Marino', id: 'SM'},
  // {name: 'Sao Tome and Principe', id: 'ST'},
  {name: 'Saudi Arabia', id: 'SA', value: 100.33},
  {name: 'Senegal', id: 'SN', value: 123},
  {name: 'Serbia and Montenegro', id: 'CS', value: 70.83},
  {name: 'Seychelles', id: 'SC', value: 160.33},
  {name: 'Sierra Leone', id: 'SL', value: 85.83},
  {name: 'Singapore', id: 'SG', value: 172},
  {name: 'Slovakia', id: 'SK', value: 114.83},
  {name: 'Slovenia', id: 'SI', value: 55},
  {name: 'Solomon Islands', id: 'SB', value: 73},
  // {name: 'Somalia', id: 'SO'},
  {name: 'South Africa', id: 'ZA', value: 76},
  // {name: 'South Georgia and the South Sandwich Islands', id: 'GS'},
  {name: 'Spain', id: 'ES', value: 46},
  {name: 'Sri Lanka', id: 'LK', value: 39},
  {name: 'Sudan', id: 'SD', value: 92.67},
  {name: 'Suriname', id: 'SR', value: 164},
  // {name: 'Svalbard and Jan Mayen', id: 'SJ'},
  // {name: 'Swaziland', id: 'SZ'},
  {name: 'Sweden', id: 'SE', value: 131.33},
  {name: 'Switzerland', id: 'CH', value: 57.67},
  // {name: 'Syrian Arab Republic', id: 'SY'},
  // {name: 'Taiwan, Province of China', id: 'TW'},
  {name: 'Tajikistan', id: 'TJ', value: 59},
  {name: 'Tanzania, United Republic of', id: 'TZ', value: 111.33},
  {name: 'Thailand', id: 'TH', value: 29.83},
  // {name: 'Timor-Leste', id: 'TL'},
  {name: 'Togo', id: 'TG', value: 148.83},
  // {name: 'Tokelau', id: 'TK'},
  {name: 'Tonga', id: 'TO', value: 75.67},
  {name: 'Trinidad and Tobago', id: 'TT', value: 148.83},
  {name: 'Tunisia', id: 'TN', value: 114.5},
  {name: 'Turkey', id: 'TR', value: 111.83},
  // {name: 'Turkmenistan', id: 'TM'},
  // {name: 'Turks and Caicos Islands', id: 'TC'},
  {name: 'Tuvalu', id: 'TV', value: 113.5},
  {name: 'Uganda', id: 'UG', value: 70.67},
  {name: 'Ukraine', id: 'UA', value: 88.83},
  {name: 'United Arab Emirates', id: 'AE', value: 156},
  {name: 'United Kingdom', id: 'GB', value: 65},
  // {name: 'United States', id: 'US'},
  // {name: 'United States Minor Outlying Islands', id: 'UM'},
  {name: 'Uruguay', id: 'UY', value: 89.83},
  {name: 'Uzbekistan', id: 'UZ', value: 161.17},
  {name: 'Vanuatu', id: 'VU', value: 53.83},
  {name: 'Venezuela', id: 'VE', value: 132.5},
  {name: 'Vietnam', id: 'VN', value: 35.67},
  {name: 'Virgin Islands, British', id: 'VG'},
  // {name: 'Virgin Islands, U.S.', id: 'VI'},
  // {name: 'Wallis and Futuna', id: 'WF'},
  // {name: 'Western Sahara', id: 'EH'},
  {name: 'Yemen', id: 'YE', value: 76},
  {name: 'Zambia', id: 'ZM', value: 111.17},
  {name: 'Zimbabwe', id: 'ZW', value: 37.5}
];

// polygonSeries.data = [
//   { id: "AF", value: 60.524 },
//   { id: "AL", value: 77.185 },
//   { id: "DZ", value: 70.874 },
//   { id: "AO", value: 51.498 },
//   { id: "AR", value: 76.128 },
//   { id: "AM", value: 74.469 },
//   { id: "AU", value: 82.364 },
//   { id: "AT", value: 80.965 },
//   { id: "AZ", value: 70.686 },
//   { id: "BH", value: 76.474 },
//   { id: "BD", value: 70.258 },
//   { id: "BY", value: 69.829 },
//   { id: "BE", value: 80.373 },
//   { id: "BJ", value: 59.165 },
//   { id: "BT", value: 67.888 },
//   { id: "BO", value: 66.969 },
//   { id: "BA", value: 76.211 },
//   { id: "BW", value: 47.152 },
//   { id: "BR", value: 73.667 },
//   { id: "BN", value: 78.35 },
//   { id: "BG", value: 73.448 },
//   { id: "BF", value: 55.932 },
//   { id: "BI", value: 53.637 },
//   { id: "KH", value: 71.577 },
//   { id: "CM", value: 54.61 },
//   { id: "CA", value: 81.323 },
//   { id: "CV", value: 74.771 },
//   { id: "CF", value: 49.517 },
//   { id: "TD", value: 50.724 },
//   { id: "CL", value: 79.691 },
//   { id: "CN", value: 75.178 },
//   { id: "CO", value: 73.835 },
//   { id: "KM", value: 60.661 },
//   { id: "CD", value: 49.643 },
//   { id: "CG", value: 58.32 },
//   { id: "CR", value: 79.712 },
//   { id: "CI", value: 50.367 },
//   { id: "HR", value: 76.881 },
//   { id: "CU", value: 79.088 },
//   { id: "CY", value: 79.674 },
//   { id: "CZ", value: 77.552 },
//   { id: "DK", value: 79.251 },
//   { id: "GL", value: 79.251 },
//   { id: "DJ", value: 61.319 },
//   { id: "DO", value: 73.181 },
//   { id: "EC", value: 76.195 },
//   { id: "EG", value: 70.933 },
//   { id: "SV", value: 72.361 },
//   { id: "GQ", value: 52.562 },
//   { id: "ER", value: 62.329 },
//   { id: "EE", value: 74.335 },
//   { id: "ET", value: 62.983 },
//   { id: "FJ", value: 69.626 },
//   { id: "FI", value: 80.362 },
//   { id: "FR", value: 81.663 },
//   { id: "GA", value: 63.115 },
//   { id: "GF", value: 79.9 },
//   { id: "GM", value: 58.59 },
//   { id: "GE", value: 74.162 },
//   { id: "DE", value: 80.578 },
//   { id: "GH", value: 60.979 },
//   { id: "GR", value: 80.593 },
//   { id: "GT", value: 71.77 },
//   { id: "GN", value: 55.865 },
//   { id: "GW", value: 54.054 },
//   { id: "GY", value: 66.134 },
//   { id: "HT", value: 62.746 },
//   { id: "HN", value: 73.503 },
//   { id: "HK", value: 83.199 },
//   { id: "HU", value: 74.491 },
//   { id: "IS", value: 81.96 },
//   { id: "IN", value: 66.168 },
//   { id: "ID", value: 70.624 },
//   { id: "IR", value: 73.736 },
//   { id: "IQ", value: 69.181 },
//   { id: "IE", value: 80.531 },
//   { id: "IL", value: 81.641 },
//   { id: "IT", value: 82.235 },
//   { id: "JM", value: 73.338 },
//   { id: "JP", value: 83.418 },
//   { id: "JO", value: 73.7 },
//   { id: "KZ", value: 66.394 },
//   { id: "KE", value: 61.115 },
//   { id: "KP", value: 69.701 },
//   { id: "KR", value: 81.294 },
//   { id: "KW", value: 74.186 },
//   { id: "KG", value: 67.37 },
//   { id: "LA", value: 67.865 },
//   { id: "LV", value: 72.045 },
//   { id: "LB", value: 79.716 },
//   { id: "LS", value: 48.947 },
//   { id: "LR", value: 60.23 },
//   { id: "LY", value: 75.13 },
//   { id: "LT", value: 71.942 },
//   { id: "LU", value: 80.371 },
//   { id: "MK", value: 75.041 },
//   { id: "MG", value: 64.28 },
//   { id: "MW", value: 54.798 },
//   { id: "MY", value: 74.836 },
//   { id: "ML", value: 54.622 },
//   { id: "MR", value: 61.39 },
//   { id: "MU", value: 73.453 },
//   { id: "MX", value: 77.281 },
//   { id: "MD", value: 68.779 },
//   { id: "MN", value: 67.286 },
//   { id: "ME", value: 74.715 },
//   { id: "MA", value: 70.714 },
//   { id: "EH", value: 70.714 },
//   { id: "MZ", value: 49.91 },
//   { id: "MM", value: 65.009 },
//   { id: "NA", value: 64.014 },
//   { id: "NP", value: 67.989 },
//   { id: "NL", value: 80.906 },
//   { id: "NZ", value: 80.982 },
//   { id: "NI", value: 74.515 },
//   { id: "NE", value: 57.934 },
//   { id: "NG", value: 52.116 },
//   { id: "NO", value: 81.367 },
//   { id: "SJ", value: 81.367 },
//   { id: "OM", value: 76.287 },
//   { id: "PK", value: 66.42 },
//   { id: "PA", value: 77.342 },
//   { id: "PG", value: 62.288 },
//   { id: "PY", value: 72.181 },
//   { id: "PE", value: 74.525 },
//   { id: "PH", value: 68.538 },
//   { id: "PL", value: 76.239 },
//   { id: "PT", value: 79.732 },
//   { id: "QA", value: 78.231 },
//   { id: "RO", value: 73.718 },
//   { id: "RU", value: 67.874 },
//   { id: "RW", value: 63.563 },
//   { id: "SA", value: 75.264 },
//   { id: "SN", value: 63.3 },
//   { id: "RS", value: 73.934 },
//   { id: "SL", value: 45.338 },
//   { id: "SG", value: 82.155 },
//   { id: "SK", value: 75.272 },
//   { id: "SI", value: 79.444 },
//   { id: "SB", value: 67.465 },
//   { id: "SO", value: 54 },
//   { id: "ZA", value: 56.271 },
//   { id: "SS", value: 54.666 },
//   { id: "ES", value: 81.958 },
//   { id: "LK", value: 74.116 },
//   { id: "SD", value: 61.875 },
//   { id: "SR", value: 70.794 },
//   { id: "SZ", value: 48.91 },
//   { id: "SE", value: 81.69 },
//   { id: "CH", value: 82.471 },
//   { id: "SY", value: 71 },
//   { id: "TW", value: 79.45 },
//   { id: "TJ", value: 67.118 },
//   { id: "TZ", value: 60.885 },
//   { id: "TH", value: 74.225 },
//   { id: "TL", value: 67.033 },
//   { id: "TG", value: 56.198 },
//   { id: "TT", value: 69.761 },
//   { id: "TN", value: 75.632 },
//   { id: "TR", value: 74.938 },
//   { id: "TM", value: 65.299 },
//   { id: "UG", value: 58.668 },
//   { id: "UA", value: 68.414 },
//   { id: "AE", value: 76.671 },
//   { id: "GB", value: 80.396 },
//   { id: "US", value: 78.797 },
//   { id: "UY", value: 77.084 },
//   { id: "UZ", value: 68.117 },
//   { id: "VE", value: 74.477 },
//   { id: "PS", value: 73.018 },
//   { id: "VN", value: 75.793 },
//   { id: "YE", value: 62.923 },
//   { id: "ZM", value: 57.037 },
//   { id: "ZW", value: 58.142 }
// ];
